#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.0.2 effective-5.10 (swiftlang-6.0.2.1.2 clang-1600.0.26.4)
#ifndef ADPOPCORNSSPSDK_SWIFT_H
#define ADPOPCORNSSPSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="AdPopcornSSPSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

SWIFT_CLASS("_TtC15AdPopcornSSPSDK8APLogger")
@interface APLogger : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, Log, open) {
  LogAll = 0,
  LogNetwork = 1,
  LogInfo = 2,
  LogError = 3,
  LogNone = 4,
};


@class AdPopcornNativeAdView;
@class UILabel;
@class UIImageView;
@class UIButton;

SWIFT_CLASS("_TtC15AdPopcornSSPSDK32APSSPAdPopcornNativeAdRenderable")
@interface APSSPAdPopcornNativeAdRenderable : NSObject
@property (nonatomic, strong) AdPopcornNativeAdView * _Nullable nativeView;
@property (nonatomic, strong) UILabel * _Nullable adTitleLabel;
@property (nonatomic, strong) UILabel * _Nullable adDescLabel;
@property (nonatomic, strong) UIImageView * _Nullable adMainImageView;
@property (nonatomic, strong) UIImageView * _Nullable adAppIconView;
@property (nonatomic, strong) UIButton * _Nullable adCTAButton;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSCoder;

SWIFT_CLASS("_TtC15AdPopcornSSPSDK21AdPopcornNativeAdView")
@interface AdPopcornNativeAdView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15AdPopcornSSPSDK17APSSPNativeAdView")
@interface APSSPNativeAdView : AdPopcornNativeAdView
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified mainImageView;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified appiconImageView;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified titleLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified descLabel;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified ctaButton;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, AdPopcornBannerSize, open) {
  AdPopcornBannerSizeBanner320x50 = 1,
  AdPopcornBannerSizeBanner320x100 = 3,
  AdPopcornBannerSizeBanner300x250 = 2,
  AdPopcornBannerSizeBannerAdaptiveSize = 4,
};

@protocol AdPopcornBannerViewDelegate;
@class NSString;
@class UIViewController;
enum AnimationType : NSInteger;

/// <h1>APBannerView</h1>
/// <ul>
///   <li>
///     placeMentID : 각 Banner 별 PlaceMentID 값
///   </li>
///   <li>
///     bannerSize : 320x50, 300x250, 320x100 size 가능, 360x185는 NAN 사용시
///   </li>
///   <li>
///     rootViewController : 화면 전환
///   </li>
///   <li>
///     adRefreshTime :  Default 시간은 60초이며, 30~120초 사이로 설정 가능. 단, -1초로 설정 시, refresh 사용 안함.
///   </li>
/// </ul>
SWIFT_CLASS("_TtC15AdPopcornSSPSDK19AdPopcornBannerView")
@interface AdPopcornBannerView : UIView
@property (nonatomic, weak) id <AdPopcornBannerViewDelegate> _Nullable delegate;
@property (nonatomic, copy) NSString * _Nullable appkey;
@property (nonatomic, copy) NSString * _Nonnull placementID;
@property (nonatomic, copy) NSString * _Nonnull message;
- (nonnull instancetype)initWithAppkey:(NSString * _Nullable)appkey placementID:(NSString * _Nonnull)placementID bannerSize:(enum AdPopcornBannerSize)bannerSize parentView:(UIView * _Nonnull)parentView rootViewController:(UIViewController * _Nullable)rootViewController adRefreshTime:(NSInteger)adRefreshTime animationType:(enum AnimationType)animationType OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithAppkey:(NSString * _Nullable)appkey placementID:(NSString * _Nonnull)placementID bannerSize:(enum AdPopcornBannerSize)bannerSize origin:(CGPoint)origin parentView:(UIView * _Nonnull)parentView rootViewController:(UIViewController * _Nullable)rootViewController adRefreshTime:(NSInteger)adRefreshTime animationType:(enum AnimationType)animationType OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
/// Banner 광고 Load
- (void)loadAd;
- (void)stop;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end


@interface AdPopcornBannerView (SWIFT_EXTENSION(AdPopcornSSPSDK))
@end

typedef SWIFT_ENUM(NSInteger, AnimationType, open) {
  AnimationTypeNone = 0,
  AnimationTypeCurlDown = 1,
  AnimationTypeCurlUp = 2,
  AnimationTypeFlipFromLeft = 3,
  AnimationTypeFlipFromRight = 4,
  AnimationTypeFadeIn = 5,
};


@interface AdPopcornBannerView (SWIFT_EXTENSION(AdPopcornSSPSDK))
- (void)setAutoBgColor:(BOOL)istrue;
@end


enum NetworkError : NSInteger;

SWIFT_PROTOCOL("_TtP15AdPopcornSSPSDK27AdPopcornBannerViewDelegate_")
@protocol AdPopcornBannerViewDelegate <NSObject>
@optional
- (void)adPopcornBannerViewLoadSuccessWithBannerView:(AdPopcornBannerView * _Nonnull)bannerView;
- (void)adPopcornBannerViewLoadFailWithBannerView:(AdPopcornBannerView * _Nonnull)bannerView error:(enum NetworkError)error;
- (void)adPopcornBannerViewClickedWithBannerView:(AdPopcornBannerView * _Nonnull)bannerView;
- (void)adPopcornBannerViewImpressionWithBannerView:(AdPopcornBannerView * _Nonnull)bannerView;
@end

typedef SWIFT_ENUM(NSInteger, AdPopcornBidding, open) {
  AdPopcornBiddingFBAudienceNetwork = 1,
  AdPopcornBiddingVungle = 2,
  AdPopcornBiddingBiddingdata = 10,
};

@protocol AdPopcornInterstitialAdDelegate;
@class UIColor;

SWIFT_CLASS("_TtC15AdPopcornSSPSDK23AdPopcornInterstitialAd")
@interface AdPopcornInterstitialAd : NSObject
@property (nonatomic, weak) id <AdPopcornInterstitialAdDelegate> _Nullable delegate;
@property (nonatomic, copy) NSString * _Nonnull placementID;
@property (nonatomic, copy) NSString * _Nullable appkey;
@property (nonatomic, copy) NSString * _Nonnull message;
@property (nonatomic, strong) UIColor * _Nonnull backgroundColor;
- (nonnull instancetype)initWithAppkey:(NSString * _Nullable)appkey placementID:(NSString * _Nonnull)placementID rootViewController:(UIViewController * _Nullable)rootViewController OBJC_DESIGNATED_INITIALIZER;
- (void)load;
- (void)presentFrom:(UIViewController * _Nonnull)from;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_PROTOCOL("_TtP15AdPopcornSSPSDK31AdPopcornInterstitialAdDelegate_")
@protocol AdPopcornInterstitialAdDelegate
@optional
- (void)adPopcornInterstitialAdLoadSuccessWithInterstitialAd:(AdPopcornInterstitialAd * _Nonnull)interstitialAd;
- (void)adPopcornInterstitialAdLoadFailWithInterstitialAd:(AdPopcornInterstitialAd * _Nonnull)interstitialAd error:(enum NetworkError)error;
- (void)adPopcorninterstitialAdShowSuccessWithInterstitialAd:(AdPopcornInterstitialAd * _Nonnull)interstitialAd;
- (void)adPopcorninterstitialAdShowFailWithInterstitialAd:(AdPopcornInterstitialAd * _Nonnull)interstitialAd;
- (void)adPopcorninterstitialAdClickedWithInterstitialAd:(AdPopcornInterstitialAd * _Nonnull)interstitialAd;
- (void)adPopcorninterstitialAdClosedWithInterstitialAd:(AdPopcornInterstitialAd * _Nonnull)interstitialAd;
@end

@protocol AdPopcornInterstitialVideoAdDelegate;

SWIFT_CLASS("_TtC15AdPopcornSSPSDK28AdPopcornInterstitialVideoAd")
@interface AdPopcornInterstitialVideoAd : NSObject
@property (nonatomic, weak) id <AdPopcornInterstitialVideoAdDelegate> _Nullable delegate;
@property (nonatomic, copy) NSString * _Nullable appkey;
@property (nonatomic, copy) NSString * _Nonnull placementID;
@property (nonatomic, copy) NSString * _Nonnull message;
- (nonnull instancetype)initWithAppkey:(NSString * _Nullable)appkey placementID:(NSString * _Nonnull)placementID rootViewController:(UIViewController * _Nullable)rootViewController OBJC_DESIGNATED_INITIALIZER;
- (void)presentFrom:(UIViewController * _Nonnull)from;
- (void)load;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_PROTOCOL("_TtP15AdPopcornSSPSDK36AdPopcornInterstitialVideoAdDelegate_")
@protocol AdPopcornInterstitialVideoAdDelegate
@optional
- (void)adPopcornInterstitialVideoAdLoadSuccessWithInterstitialVideoAd:(AdPopcornInterstitialVideoAd * _Nonnull)interstitialVideoAd;
- (void)adPopcornInterstitialVideoAdLoadFailWithInterstitialVideoAd:(AdPopcornInterstitialVideoAd * _Nonnull)interstitialVideoAd error:(enum NetworkError)error;
- (void)adPopcorninterstitialVideoAdShowSuccessWithInterstitialVideoAd:(AdPopcornInterstitialVideoAd * _Nonnull)interstitialVideoAd;
- (void)adPopcorninterstitialVideoAdShowFailWithInterstitialVideoAd:(AdPopcornInterstitialVideoAd * _Nonnull)interstitialVideoAd;
- (void)adPopcorninterstitialVideoAdClickedWithInterstitialVideoAd:(AdPopcornInterstitialVideoAd * _Nonnull)interstitialVideoAd;
- (void)adPopcorninterstitialVideoAdClosedWithInterstitialVideoAd:(AdPopcornInterstitialVideoAd * _Nonnull)interstitialVideoAd;
@end

@protocol AdPopcornNativeAdDelegate;

SWIFT_CLASS("_TtC15AdPopcornSSPSDK17AdPopcornNativeAd")
@interface AdPopcornNativeAd : UIView
@property (nonatomic, weak) id <AdPopcornNativeAdDelegate> _Nullable delegate;
@property (nonatomic, copy) NSString * _Nullable appkey;
@property (nonatomic, copy) NSString * _Nonnull placementID;
@property (nonatomic, copy) NSString * _Nonnull message;
/// Mediation
@property (nonatomic, strong) NSObject * _Nullable adMobRenderable;
@property (nonatomic, strong) NSObject * _Nullable namRenderable;
@property (nonatomic, strong) NSObject * _Nullable adfitRenderable;
@property (nonatomic, strong) NSObject * _Nullable adopRenderable;
@property (nonatomic, strong) NSObject * _Nullable vungleRenderable;
@property (nonatomic, strong) NSObject * _Nullable applovinMaxRenderable;
@property (nonatomic, strong) NSObject * _Nullable FBANNativeRenderable;
@property (nonatomic, strong) NSObject * _Nullable FBANnativeBannerRenderable;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithAppkey:(NSString * _Nullable)appkey placementID:(NSString * _Nonnull)placementID rootViewController:(UIViewController * _Nullable)rootViewController OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)load;
- (void)stop;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end


@interface AdPopcornNativeAd (SWIFT_EXTENSION(AdPopcornSSPSDK))
- (void)bindAdPopcronRendererWithAdPopcornRender:(APSSPAdPopcornNativeAdRenderable * _Nonnull)adPopcornRender useTemplate:(BOOL)useTemplate;
@end



SWIFT_PROTOCOL("_TtP15AdPopcornSSPSDK25AdPopcornNativeAdDelegate_")
@protocol AdPopcornNativeAdDelegate <NSObject>
@optional
- (void)adPopcornNativeAdLoadSuccessWithNativewAdView:(AdPopcornNativeAd * _Nonnull)nativewAdView;
- (void)adPopcornNativeAdLoadFailWithNativewAdView:(AdPopcornNativeAd * _Nonnull)nativewAdView error:(enum NetworkError)error;
- (void)adPopcornNativeAdClickedWithNativewAd:(AdPopcornNativeAd * _Nonnull)nativewAd;
- (void)adPopcornNativeAdImpressionWithNativewAd:(AdPopcornNativeAd * _Nonnull)nativewAd;
@end


@protocol AdPopcornRewardVideoAdDelegate;

SWIFT_CLASS("_TtC15AdPopcornSSPSDK22AdPopcornRewardVideoAd")
@interface AdPopcornRewardVideoAd : NSObject
@property (nonatomic, weak) id <AdPopcornRewardVideoAdDelegate> _Nullable delegate;
@property (nonatomic, copy) NSString * _Nullable appkey;
@property (nonatomic, copy) NSString * _Nonnull placementID;
@property (nonatomic, copy) NSString * _Nonnull message;
- (nonnull instancetype)initWithAppkey:(NSString * _Nullable)appkey placementID:(NSString * _Nonnull)placementID rootViewController:(UIViewController * _Nullable)rootViewController OBJC_DESIGNATED_INITIALIZER;
- (void)presentFrom:(UIViewController * _Nonnull)from;
- (void)load;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


enum MediationCompany : NSInteger;

SWIFT_PROTOCOL("_TtP15AdPopcornSSPSDK30AdPopcornRewardVideoAdDelegate_")
@protocol AdPopcornRewardVideoAdDelegate
@optional
- (void)adPopcornRewardVideoAdLoadSuccessWithRewardVideoAd:(AdPopcornRewardVideoAd * _Nonnull)rewardVideoAd;
- (void)adPopcornRewardVideoAdLoadFailWithRewardVideoAd:(AdPopcornRewardVideoAd * _Nonnull)rewardVideoAd error:(enum NetworkError)error;
- (void)adPopcornRewardVideoAdShowSuccessWithRewardVideoAd:(AdPopcornRewardVideoAd * _Nonnull)rewardVideoAd;
- (void)adPopcornRewardVideoAdShowFailWithRewardVideoAd:(AdPopcornRewardVideoAd * _Nonnull)rewardVideoAd;
- (void)adPopcornRewardVideoAdClickedWithRewardVideoAd:(AdPopcornRewardVideoAd * _Nonnull)rewardVideoAd;
- (void)adPopcornRewardVideoAdClosedWithRewardVideoAd:(AdPopcornRewardVideoAd * _Nonnull)rewardVideoAd;
- (void)adPopcornRewardVideoAdCompletedWithRewardVideoAd:(AdPopcornRewardVideoAd * _Nonnull)rewardVideoAd currenMediationType:(enum MediationCompany)currenMediationType;
@end


SWIFT_CLASS("_TtC15AdPopcornSSPSDK12AdPopcornSSP")
@interface AdPopcornSSP : NSObject
/// 리워드 비디오. 사용시 해당 ID 값 필수
+ (void)setUSerIDWithUsn:(NSString * _Nonnull)usn;
+ (void)initializeSDKWithAppKey:(NSString * _Nonnull)appKey;
+ (void)setLogType:(enum Log)type;
+ (void)presentCSViewController:(UIViewController * _Nonnull)rootViewController userID:(NSString * _Nonnull)userID;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, MediationCompany, open) {
  MediationCompanyAdPopcorn = 0,
  MediationCompanyAdMob = 1,
  MediationCompanyFacebook_Audience_Network = 2,
  MediationCompanyCauly = 4,
  MediationCompanyMezzoMedia = 5,
  MediationCompanyUnityAds = 7,
  MediationCompanyMintegral = 8,
  MediationCompanyAdFit = 10,
  MediationCompanyVungle = 14,
  MediationCompanyAppLovin_MAX = 15,
  MediationCompanyFyber = 16,
  MediationCompanyPangle = 18,
  MediationCompanyAppLovin = 21,
  MediationCompanyNAM = 22,
  MediationCompanyADOP = 24,
  MediationCompanyError = 99999,
};

typedef SWIFT_ENUM(NSInteger, NetworkError, open) {
/// 200, 서버 내부 Error
  NetworkErrorServerError = 200,
/// 1000, 요청 정보 Error
  NetworkErrorParameterError = 1000,
/// 2000, 요청 정보 appkey Error
  NetworkErrorAppKeyError = 2000,
/// 2030, 요청 정보 PlaceMentID Error
  NetworkErrorPlacementIDError = 2030,
/// 2100, Campain List Empty Error
  NetworkErrorEmptyCampaignError = 2100,
  NetworkErrorNativePlacementNoInitialized = 3200,
/// 3300, Native 지면 asset관련 설정 정보 확인 Error
  NetworkErrorAssetError = 3300,
  NetworkErrorMediationInvalidIntegrationKey = 4000,
  NetworkErrorMediationAdapterNotInitialized = 4001,
  NetworkErrorServerTimeout = 5000,
  NetworkErrorLoadAdFailed = 5001,
/// 5002, No Advertisement Error
  NetworkErrorNoAdError = 5002,
  NetworkErrorNoInterstitialLoaded = 5003,
  NetworkErrorNoRewardVideoAdLoaded = 5005,
  NetworkErrorGdprConsentUnavailable = 5008,
  NetworkErrorNoInterstitialVideoAdLoaded = 5009,
/// 8888, decoding Error
  NetworkErrorDecodingError = 8888,
/// 9999, 알 수 없는 Server Error
  NetworkErrorUnknownServerError = 9999,
/// 임의 설정은 6자리로 처리하였음
/// mediation 광고가 없을 때 (임의로 설정)
  NetworkErrorNextMediation = 100000,
/// vast parsing 에서 error 가 발생했을 경우  (임의로 설정)
  NetworkErrorVastParsingError = 200000,
/// delegate 연결 실패로 인한 error
  NetworkErrorDelegateError = 300000,
/// native View 직접 custom 해야 함
  NetworkErrorNativeViewCustomError = 300001,
/// rootViewController 연결 안되어 있을 때
  NetworkErrorRootviewControllerError = 300002,
};
static NSString * _Nonnull const NetworkErrorDomain = @"AdPopcornSSPSDK.NetworkError";




#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 6.0.2 effective-5.10 (swiftlang-6.0.2.1.2 clang-1600.0.26.4)
#ifndef ADPOPCORNSSPSDK_SWIFT_H
#define ADPOPCORNSSPSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="AdPopcornSSPSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

SWIFT_CLASS("_TtC15AdPopcornSSPSDK8APLogger")
@interface APLogger : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, Log, open) {
  LogAll = 0,
  LogNetwork = 1,
  LogInfo = 2,
  LogError = 3,
  LogNone = 4,
};


@class AdPopcornNativeAdView;
@class UILabel;
@class UIImageView;
@class UIButton;

SWIFT_CLASS("_TtC15AdPopcornSSPSDK32APSSPAdPopcornNativeAdRenderable")
@interface APSSPAdPopcornNativeAdRenderable : NSObject
@property (nonatomic, strong) AdPopcornNativeAdView * _Nullable nativeView;
@property (nonatomic, strong) UILabel * _Nullable adTitleLabel;
@property (nonatomic, strong) UILabel * _Nullable adDescLabel;
@property (nonatomic, strong) UIImageView * _Nullable adMainImageView;
@property (nonatomic, strong) UIImageView * _Nullable adAppIconView;
@property (nonatomic, strong) UIButton * _Nullable adCTAButton;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSCoder;

SWIFT_CLASS("_TtC15AdPopcornSSPSDK21AdPopcornNativeAdView")
@interface AdPopcornNativeAdView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15AdPopcornSSPSDK17APSSPNativeAdView")
@interface APSSPNativeAdView : AdPopcornNativeAdView
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified mainImageView;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified appiconImageView;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified titleLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified descLabel;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified ctaButton;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, AdPopcornBannerSize, open) {
  AdPopcornBannerSizeBanner320x50 = 1,
  AdPopcornBannerSizeBanner320x100 = 3,
  AdPopcornBannerSizeBanner300x250 = 2,
  AdPopcornBannerSizeBannerAdaptiveSize = 4,
};

@protocol AdPopcornBannerViewDelegate;
@class NSString;
@class UIViewController;
enum AnimationType : NSInteger;

/// <h1>APBannerView</h1>
/// <ul>
///   <li>
///     placeMentID : 각 Banner 별 PlaceMentID 값
///   </li>
///   <li>
///     bannerSize : 320x50, 300x250, 320x100 size 가능, 360x185는 NAN 사용시
///   </li>
///   <li>
///     rootViewController : 화면 전환
///   </li>
///   <li>
///     adRefreshTime :  Default 시간은 60초이며, 30~120초 사이로 설정 가능. 단, -1초로 설정 시, refresh 사용 안함.
///   </li>
/// </ul>
SWIFT_CLASS("_TtC15AdPopcornSSPSDK19AdPopcornBannerView")
@interface AdPopcornBannerView : UIView
@property (nonatomic, weak) id <AdPopcornBannerViewDelegate> _Nullable delegate;
@property (nonatomic, copy) NSString * _Nullable appkey;
@property (nonatomic, copy) NSString * _Nonnull placementID;
@property (nonatomic, copy) NSString * _Nonnull message;
- (nonnull instancetype)initWithAppkey:(NSString * _Nullable)appkey placementID:(NSString * _Nonnull)placementID bannerSize:(enum AdPopcornBannerSize)bannerSize parentView:(UIView * _Nonnull)parentView rootViewController:(UIViewController * _Nullable)rootViewController adRefreshTime:(NSInteger)adRefreshTime animationType:(enum AnimationType)animationType OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithAppkey:(NSString * _Nullable)appkey placementID:(NSString * _Nonnull)placementID bannerSize:(enum AdPopcornBannerSize)bannerSize origin:(CGPoint)origin parentView:(UIView * _Nonnull)parentView rootViewController:(UIViewController * _Nullable)rootViewController adRefreshTime:(NSInteger)adRefreshTime animationType:(enum AnimationType)animationType OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
/// Banner 광고 Load
- (void)loadAd;
- (void)stop;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end


@interface AdPopcornBannerView (SWIFT_EXTENSION(AdPopcornSSPSDK))
@end

typedef SWIFT_ENUM(NSInteger, AnimationType, open) {
  AnimationTypeNone = 0,
  AnimationTypeCurlDown = 1,
  AnimationTypeCurlUp = 2,
  AnimationTypeFlipFromLeft = 3,
  AnimationTypeFlipFromRight = 4,
  AnimationTypeFadeIn = 5,
};


@interface AdPopcornBannerView (SWIFT_EXTENSION(AdPopcornSSPSDK))
- (void)setAutoBgColor:(BOOL)istrue;
@end


enum NetworkError : NSInteger;

SWIFT_PROTOCOL("_TtP15AdPopcornSSPSDK27AdPopcornBannerViewDelegate_")
@protocol AdPopcornBannerViewDelegate <NSObject>
@optional
- (void)adPopcornBannerViewLoadSuccessWithBannerView:(AdPopcornBannerView * _Nonnull)bannerView;
- (void)adPopcornBannerViewLoadFailWithBannerView:(AdPopcornBannerView * _Nonnull)bannerView error:(enum NetworkError)error;
- (void)adPopcornBannerViewClickedWithBannerView:(AdPopcornBannerView * _Nonnull)bannerView;
- (void)adPopcornBannerViewImpressionWithBannerView:(AdPopcornBannerView * _Nonnull)bannerView;
@end

typedef SWIFT_ENUM(NSInteger, AdPopcornBidding, open) {
  AdPopcornBiddingFBAudienceNetwork = 1,
  AdPopcornBiddingVungle = 2,
  AdPopcornBiddingBiddingdata = 10,
};

@protocol AdPopcornInterstitialAdDelegate;
@class UIColor;

SWIFT_CLASS("_TtC15AdPopcornSSPSDK23AdPopcornInterstitialAd")
@interface AdPopcornInterstitialAd : NSObject
@property (nonatomic, weak) id <AdPopcornInterstitialAdDelegate> _Nullable delegate;
@property (nonatomic, copy) NSString * _Nonnull placementID;
@property (nonatomic, copy) NSString * _Nullable appkey;
@property (nonatomic, copy) NSString * _Nonnull message;
@property (nonatomic, strong) UIColor * _Nonnull backgroundColor;
- (nonnull instancetype)initWithAppkey:(NSString * _Nullable)appkey placementID:(NSString * _Nonnull)placementID rootViewController:(UIViewController * _Nullable)rootViewController OBJC_DESIGNATED_INITIALIZER;
- (void)load;
- (void)presentFrom:(UIViewController * _Nonnull)from;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_PROTOCOL("_TtP15AdPopcornSSPSDK31AdPopcornInterstitialAdDelegate_")
@protocol AdPopcornInterstitialAdDelegate
@optional
- (void)adPopcornInterstitialAdLoadSuccessWithInterstitialAd:(AdPopcornInterstitialAd * _Nonnull)interstitialAd;
- (void)adPopcornInterstitialAdLoadFailWithInterstitialAd:(AdPopcornInterstitialAd * _Nonnull)interstitialAd error:(enum NetworkError)error;
- (void)adPopcorninterstitialAdShowSuccessWithInterstitialAd:(AdPopcornInterstitialAd * _Nonnull)interstitialAd;
- (void)adPopcorninterstitialAdShowFailWithInterstitialAd:(AdPopcornInterstitialAd * _Nonnull)interstitialAd;
- (void)adPopcorninterstitialAdClickedWithInterstitialAd:(AdPopcornInterstitialAd * _Nonnull)interstitialAd;
- (void)adPopcorninterstitialAdClosedWithInterstitialAd:(AdPopcornInterstitialAd * _Nonnull)interstitialAd;
@end

@protocol AdPopcornInterstitialVideoAdDelegate;

SWIFT_CLASS("_TtC15AdPopcornSSPSDK28AdPopcornInterstitialVideoAd")
@interface AdPopcornInterstitialVideoAd : NSObject
@property (nonatomic, weak) id <AdPopcornInterstitialVideoAdDelegate> _Nullable delegate;
@property (nonatomic, copy) NSString * _Nullable appkey;
@property (nonatomic, copy) NSString * _Nonnull placementID;
@property (nonatomic, copy) NSString * _Nonnull message;
- (nonnull instancetype)initWithAppkey:(NSString * _Nullable)appkey placementID:(NSString * _Nonnull)placementID rootViewController:(UIViewController * _Nullable)rootViewController OBJC_DESIGNATED_INITIALIZER;
- (void)presentFrom:(UIViewController * _Nonnull)from;
- (void)load;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_PROTOCOL("_TtP15AdPopcornSSPSDK36AdPopcornInterstitialVideoAdDelegate_")
@protocol AdPopcornInterstitialVideoAdDelegate
@optional
- (void)adPopcornInterstitialVideoAdLoadSuccessWithInterstitialVideoAd:(AdPopcornInterstitialVideoAd * _Nonnull)interstitialVideoAd;
- (void)adPopcornInterstitialVideoAdLoadFailWithInterstitialVideoAd:(AdPopcornInterstitialVideoAd * _Nonnull)interstitialVideoAd error:(enum NetworkError)error;
- (void)adPopcorninterstitialVideoAdShowSuccessWithInterstitialVideoAd:(AdPopcornInterstitialVideoAd * _Nonnull)interstitialVideoAd;
- (void)adPopcorninterstitialVideoAdShowFailWithInterstitialVideoAd:(AdPopcornInterstitialVideoAd * _Nonnull)interstitialVideoAd;
- (void)adPopcorninterstitialVideoAdClickedWithInterstitialVideoAd:(AdPopcornInterstitialVideoAd * _Nonnull)interstitialVideoAd;
- (void)adPopcorninterstitialVideoAdClosedWithInterstitialVideoAd:(AdPopcornInterstitialVideoAd * _Nonnull)interstitialVideoAd;
@end

@protocol AdPopcornNativeAdDelegate;

SWIFT_CLASS("_TtC15AdPopcornSSPSDK17AdPopcornNativeAd")
@interface AdPopcornNativeAd : UIView
@property (nonatomic, weak) id <AdPopcornNativeAdDelegate> _Nullable delegate;
@property (nonatomic, copy) NSString * _Nullable appkey;
@property (nonatomic, copy) NSString * _Nonnull placementID;
@property (nonatomic, copy) NSString * _Nonnull message;
/// Mediation
@property (nonatomic, strong) NSObject * _Nullable adMobRenderable;
@property (nonatomic, strong) NSObject * _Nullable namRenderable;
@property (nonatomic, strong) NSObject * _Nullable adfitRenderable;
@property (nonatomic, strong) NSObject * _Nullable adopRenderable;
@property (nonatomic, strong) NSObject * _Nullable vungleRenderable;
@property (nonatomic, strong) NSObject * _Nullable applovinMaxRenderable;
@property (nonatomic, strong) NSObject * _Nullable FBANNativeRenderable;
@property (nonatomic, strong) NSObject * _Nullable FBANnativeBannerRenderable;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithAppkey:(NSString * _Nullable)appkey placementID:(NSString * _Nonnull)placementID rootViewController:(UIViewController * _Nullable)rootViewController OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)load;
- (void)stop;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end


@interface AdPopcornNativeAd (SWIFT_EXTENSION(AdPopcornSSPSDK))
- (void)bindAdPopcronRendererWithAdPopcornRender:(APSSPAdPopcornNativeAdRenderable * _Nonnull)adPopcornRender useTemplate:(BOOL)useTemplate;
@end



SWIFT_PROTOCOL("_TtP15AdPopcornSSPSDK25AdPopcornNativeAdDelegate_")
@protocol AdPopcornNativeAdDelegate <NSObject>
@optional
- (void)adPopcornNativeAdLoadSuccessWithNativewAdView:(AdPopcornNativeAd * _Nonnull)nativewAdView;
- (void)adPopcornNativeAdLoadFailWithNativewAdView:(AdPopcornNativeAd * _Nonnull)nativewAdView error:(enum NetworkError)error;
- (void)adPopcornNativeAdClickedWithNativewAd:(AdPopcornNativeAd * _Nonnull)nativewAd;
- (void)adPopcornNativeAdImpressionWithNativewAd:(AdPopcornNativeAd * _Nonnull)nativewAd;
@end


@protocol AdPopcornRewardVideoAdDelegate;

SWIFT_CLASS("_TtC15AdPopcornSSPSDK22AdPopcornRewardVideoAd")
@interface AdPopcornRewardVideoAd : NSObject
@property (nonatomic, weak) id <AdPopcornRewardVideoAdDelegate> _Nullable delegate;
@property (nonatomic, copy) NSString * _Nullable appkey;
@property (nonatomic, copy) NSString * _Nonnull placementID;
@property (nonatomic, copy) NSString * _Nonnull message;
- (nonnull instancetype)initWithAppkey:(NSString * _Nullable)appkey placementID:(NSString * _Nonnull)placementID rootViewController:(UIViewController * _Nullable)rootViewController OBJC_DESIGNATED_INITIALIZER;
- (void)presentFrom:(UIViewController * _Nonnull)from;
- (void)load;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


enum MediationCompany : NSInteger;

SWIFT_PROTOCOL("_TtP15AdPopcornSSPSDK30AdPopcornRewardVideoAdDelegate_")
@protocol AdPopcornRewardVideoAdDelegate
@optional
- (void)adPopcornRewardVideoAdLoadSuccessWithRewardVideoAd:(AdPopcornRewardVideoAd * _Nonnull)rewardVideoAd;
- (void)adPopcornRewardVideoAdLoadFailWithRewardVideoAd:(AdPopcornRewardVideoAd * _Nonnull)rewardVideoAd error:(enum NetworkError)error;
- (void)adPopcornRewardVideoAdShowSuccessWithRewardVideoAd:(AdPopcornRewardVideoAd * _Nonnull)rewardVideoAd;
- (void)adPopcornRewardVideoAdShowFailWithRewardVideoAd:(AdPopcornRewardVideoAd * _Nonnull)rewardVideoAd;
- (void)adPopcornRewardVideoAdClickedWithRewardVideoAd:(AdPopcornRewardVideoAd * _Nonnull)rewardVideoAd;
- (void)adPopcornRewardVideoAdClosedWithRewardVideoAd:(AdPopcornRewardVideoAd * _Nonnull)rewardVideoAd;
- (void)adPopcornRewardVideoAdCompletedWithRewardVideoAd:(AdPopcornRewardVideoAd * _Nonnull)rewardVideoAd currenMediationType:(enum MediationCompany)currenMediationType;
@end


SWIFT_CLASS("_TtC15AdPopcornSSPSDK12AdPopcornSSP")
@interface AdPopcornSSP : NSObject
/// 리워드 비디오. 사용시 해당 ID 값 필수
+ (void)setUSerIDWithUsn:(NSString * _Nonnull)usn;
+ (void)initializeSDKWithAppKey:(NSString * _Nonnull)appKey;
+ (void)setLogType:(enum Log)type;
+ (void)presentCSViewController:(UIViewController * _Nonnull)rootViewController userID:(NSString * _Nonnull)userID;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, MediationCompany, open) {
  MediationCompanyAdPopcorn = 0,
  MediationCompanyAdMob = 1,
  MediationCompanyFacebook_Audience_Network = 2,
  MediationCompanyCauly = 4,
  MediationCompanyMezzoMedia = 5,
  MediationCompanyUnityAds = 7,
  MediationCompanyMintegral = 8,
  MediationCompanyAdFit = 10,
  MediationCompanyVungle = 14,
  MediationCompanyAppLovin_MAX = 15,
  MediationCompanyFyber = 16,
  MediationCompanyPangle = 18,
  MediationCompanyAppLovin = 21,
  MediationCompanyNAM = 22,
  MediationCompanyADOP = 24,
  MediationCompanyError = 99999,
};

typedef SWIFT_ENUM(NSInteger, NetworkError, open) {
/// 200, 서버 내부 Error
  NetworkErrorServerError = 200,
/// 1000, 요청 정보 Error
  NetworkErrorParameterError = 1000,
/// 2000, 요청 정보 appkey Error
  NetworkErrorAppKeyError = 2000,
/// 2030, 요청 정보 PlaceMentID Error
  NetworkErrorPlacementIDError = 2030,
/// 2100, Campain List Empty Error
  NetworkErrorEmptyCampaignError = 2100,
  NetworkErrorNativePlacementNoInitialized = 3200,
/// 3300, Native 지면 asset관련 설정 정보 확인 Error
  NetworkErrorAssetError = 3300,
  NetworkErrorMediationInvalidIntegrationKey = 4000,
  NetworkErrorMediationAdapterNotInitialized = 4001,
  NetworkErrorServerTimeout = 5000,
  NetworkErrorLoadAdFailed = 5001,
/// 5002, No Advertisement Error
  NetworkErrorNoAdError = 5002,
  NetworkErrorNoInterstitialLoaded = 5003,
  NetworkErrorNoRewardVideoAdLoaded = 5005,
  NetworkErrorGdprConsentUnavailable = 5008,
  NetworkErrorNoInterstitialVideoAdLoaded = 5009,
/// 8888, decoding Error
  NetworkErrorDecodingError = 8888,
/// 9999, 알 수 없는 Server Error
  NetworkErrorUnknownServerError = 9999,
/// 임의 설정은 6자리로 처리하였음
/// mediation 광고가 없을 때 (임의로 설정)
  NetworkErrorNextMediation = 100000,
/// vast parsing 에서 error 가 발생했을 경우  (임의로 설정)
  NetworkErrorVastParsingError = 200000,
/// delegate 연결 실패로 인한 error
  NetworkErrorDelegateError = 300000,
/// native View 직접 custom 해야 함
  NetworkErrorNativeViewCustomError = 300001,
/// rootViewController 연결 안되어 있을 때
  NetworkErrorRootviewControllerError = 300002,
};
static NSString * _Nonnull const NetworkErrorDomain = @"AdPopcornSSPSDK.NetworkError";




#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
